#
# Docker NodeJS Typescript Starter
# Example Docker Compose file
#

# For more information about the directives defined here:
# https://docs.docker.com/compose/compose-file/

# Docker compose file version
version: "3.8"

services:
  app:
    build: .
    working_dir: /app
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/app
      - /app/node_modules/bcrypt
    command: npm run watch2
    depends_on:
      - db
      - redis
    stdin_open: true
    tty: true

  redis:
    image: redis:alpine
    container_name: cache
    ports:
      - ${HOST_PORT_REDIS}:${CONTAINER_PORT_REDIS}
    volumes:
      - ./redis-data:/data

  db:
    image: mongo:5.0.3
    container_name: mongodb
    ports:
      - ${HOST_PORT}:${CONTAINER_PORT}
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    env_file:
      - .env
    restart: always
    command: mongod --auth
    volumes:
      #add persistent storage
      - db:/data/db
      #add path to startup script
      - ./entrypoint/:/docker-entrypoint-initdb.d/

volumes:
  db:
